// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/civilizations/generate": {
            "post": {
                "description": "Rolls a fresh civilization via the factory LLM pipeline. Returns the civ and the planet that seeded it. No persistence.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "civilizations"
                ],
                "summary": "Generate a civilization",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Seed override; defaults to time-based random",
                        "name": "seed",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "LLM model override (e.g. gpt-4o)",
                        "name": "model",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ civilization, planet }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "generation error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "OPENAI_API_KEY not configured",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Returns \"ok\" if the server is running.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/player": {
            "get": {
                "description": "Looks up an existing player by id, or creates a new player (with an active ship) if id is missing or not found.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "summary": "Get or create a player",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Existing player UUID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.PlayerResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/ships/generate": {
            "post": {
                "description": "Rolls a ship via the factory and persists it onto the player's active ship. Defaults to the player's seed; pass ?seed= to override.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ships"
                ],
                "summary": "Generate a ship loadout",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Player UUID",
                        "name": "player_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Optional seed override",
                        "name": "seed",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ship loadout JSON",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "missing player_id query param",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "no active ship for player",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.PlayerResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "seed": {
                    "type": "integer"
                },
                "ship": {
                    "$ref": "#/definitions/handlers.ShipResponse"
                }
            }
        },
        "handlers.ShipResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "loadout": {
                    "type": "object"
                },
                "state": {
                    "type": "object"
                },
                "status": {
                    "type": "string"
                },
                "transform": {
                    "type": "object"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ThereExists API",
	Description:      "Backend API for the ThereExists game.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
